### ISSUE TITLE
Indexed geometry has same vertices as non indexed

### ISSUE THREAD

**Issue by madferro** [Fyrestar/THREE.BufferGeometry-toIndexed#1]
Hello, i'm trying to use your function but i don't understand how resulting indexed geometry has the same vertices of the starting non indexed geometry.
My code is this:

const geometry = new THREE.TetrahedronGeometry(10);
const indexdGeometry = geometry.toIndexed();

The resulting position attribute of "indexedGeometry" still has 12 vertices, while i expected only 4.
Can you help me please?

Thank you very very much in advance.

Alessandro

**Comment by Fyrestar** [comment]
Only vertices sharing the same attribute values are merged so UVs or normals that are often not shared in some place won't get distorted. The primitives in Three usually do per-segment or per-face individuals to assign material groups, so that might be the reason.

However you can try

```js
const geometry = new THREE.TetrahedronGeometry(10);
const indexdGeometry = geometry.toIndexed( false );
```

In order to ignore all other attributes and merge by position only.

**Comment by madferro** [comment]
Oh yes, It works! Thank you very very very much! Awesome work :}
